-- 1. Tabla Roles
CREATE TABLE IF NOT EXISTS rols (
    idrol BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL
);

-- 2. Tabla Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    email_verified_at TIMESTAMP NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    idrol BIGINT NULL,
    CONSTRAINT fk_users_rol FOREIGN KEY (idrol) REFERENCES rols (idrol) ON DELETE SET NULL
);

-- 3. Tabla Doctor
CREATE TABLE IF NOT EXISTS doctor (
    iddoctor BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    "DNI" VARCHAR(20) UNIQUE NULL,
    especialidad VARCHAR(255) NULL,
    sueldo DECIMAL(10, 2) NULL,
    iduser BIGINT NULL,
    CONSTRAINT fk_doctor_user FOREIGN KEY (iduser) REFERENCES users (id)
);

-- 4. Tabla Enfermera (Nota: Manteniendo nombre 'efermera' por compatibilidad)
CREATE TABLE IF NOT EXISTS efermera (
    idenfermera BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    "DNI" VARCHAR(20) UNIQUE NULL,
    numero VARCHAR(255) NULL,
    imagen VARCHAR(255) NULL,
    iduser BIGINT NULL,
    CONSTRAINT fk_enfermera_user FOREIGN KEY (iduser) REFERENCES users (id)
);

-- 5. Tabla Paciente
CREATE TABLE IF NOT EXISTS paciente (
    idpaciente BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    "DNI" VARCHAR(20) UNIQUE NULL,
    sexo VARCHAR(50) NULL,
    fecha_nacimiento DATE NULL,
    telefono VARCHAR(50) NULL,
    iduser BIGINT NULL,
    CONSTRAINT fk_paciente_user FOREIGN KEY (iduser) REFERENCES users (id)
);

-- 6. Tabla Cita
CREATE TABLE IF NOT EXISTS cita (
    idcita BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_cita DATE NULL,
    hora_cita TIME NULL,
    motivo TEXT NULL,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    idpaciente BIGINT NULL,
    iddoctor BIGINT NULL,
    idenfermera BIGINT NULL,
    CONSTRAINT fk_cita_paciente FOREIGN KEY (idpaciente) REFERENCES paciente (idpaciente),
    CONSTRAINT fk_cita_doctor FOREIGN KEY (iddoctor) REFERENCES doctor (iddoctor),
    CONSTRAINT fk_cita_enfermera FOREIGN KEY (idenfermera) REFERENCES efermera (idenfermera)
);

-- 7. Tabla Triaje
CREATE TABLE IF NOT EXISTS triaje (
    idtriaje BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idcita BIGINT NOT NULL,
    edad INTEGER NULL,
    talla FLOAT NULL,
    peso FLOAT NULL,
    "BMI" FLOAT NULL,
    grosor_piel FLOAT NULL,
    observaciones TEXT NULL,
    CONSTRAINT fk_triaje_cita FOREIGN KEY (idcita) REFERENCES cita (idcita) ON DELETE CASCADE
);

-- 8. Tabla Prediccion
CREATE TABLE IF NOT EXISTS prediccion (
    idprediccion BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idcita BIGINT NOT NULL,
    glucosa FLOAT NULL,
    presion_sanguinea FLOAT NULL,
    grosor_piel FLOAT NULL,
    insulina FLOAT NULL,
    "BMI" FLOAT NULL,
    pedigree FLOAT NULL,
    embarazos INTEGER NULL,
    edad INTEGER NULL,
    resultado FLOAT NULL,
    observacion TEXT NULL,
    analisis_ia TEXT NULL,
    timer VARCHAR(255) NULL,
    timer_inicio VARCHAR(255) NULL,
    timer_parada VARCHAR(255) NULL,
    validar_prediccion BOOLEAN DEFAULT FALSE,
    attachment_paths JSONB NULL,
    attachment_names JSONB NULL,
    CONSTRAINT fk_prediccion_cita FOREIGN KEY (idcita) REFERENCES cita (idcita) ON DELETE CASCADE
);

-- Tablas auxiliares de Laravel
CREATE TABLE IF NOT EXISTS migrations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    migration VARCHAR(255) NOT NULL,
    batch INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    email VARCHAR(255) PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id VARCHAR(255) PRIMARY KEY,
    user_id BIGINT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS cache (
    key VARCHAR(255) PRIMARY KEY,
    value TEXT NOT NULL,
    expiration INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS cache_locks (
    key VARCHAR(255) PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    expiration INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    queue VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    attempts SMALLINT NOT NULL,
    reserved_at INTEGER NULL,
    available_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL
);
